name: build readme
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golang
        uses: actions/setup-go@v2
      - name: gen
        run:
          go run .github/til.go
      - name: Commit and push if README changed
        run: |-
          git diff
          git config --global user.email "stanleylee0707@gmail.com"
          git config --global user.name "leejh-77"
          git diff --quiet || (git add README.md && git commit -m "Updated README")
          git push
